<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Membre__CLASSMETADATA__' => 0,
'App__Entity__Sikla0__CLASSMETADATA__' => 1,
'App__Entity__Transaction__CLASSMETADATA__' => 2,
'App__Entity__TypeTransaction__CLASSMETADATA__' => 3,
'App__Entity__Utilisateur__CLASSMETADATA__' => 4,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Membre',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\MembreRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'date' => $o[2],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                ],
            ],
            'table' => [
                [
                    'name' => 'membre',
                ],
            ],
            'associationMappings' => [
                [
                    'utilisateur' => $o[3],
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\Membre',
                4 => 'utilisateur_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'date',
            ],
            'columnName' => [
                1 => 'id',
                'date',
            ],
            'cascade' => [
                3 => [
                    'persist',
                    'remove',
                ],
            ],
            'fetch' => [
                3 => 2,
            ],
            'sourceEntity' => [
                3 => 'App\\Entity\\Membre',
            ],
            'sourceToTargetKeyColumns' => [
                3 => [
                    'utilisateur_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                3 => [
                    'id' => 'utilisateur_id',
                ],
            ],
            'joinColumns' => [
                3 => [
                    $o[4],
                ],
            ],
            'joinColumnFieldNames' => [
                3 => [
                    'utilisateur_id' => 'utilisateur_id',
                ],
            ],
            'deferrable' => [
                4 => false,
            ],
            'unique' => [
                4 => true,
            ],
            'nullable' => [
                4 => false,
            ],
            'referencedColumnName' => [
                4 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                3 => 'utilisateur',
            ],
            'targetEntity' => [
                3 => 'App\\Entity\\Utilisateur',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Sikla0',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\Sikla0Repository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'date' => $o[2],
                    'realise' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'realise' => 'realise',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'realise' => 'realise',
                ],
            ],
            'table' => [
                [
                    'name' => 'sikla0',
                ],
            ],
            'associationMappings' => [
                [
                    'utilisateur' => $o[4],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\Sikla0',
                5 => 'utilisateur_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'date',
                'realise',
            ],
            'columnName' => [
                1 => 'id',
                'date',
                'realise',
            ],
            'nullable' => [
                3 => true,
                5 => false,
            ],
            'cascade' => [
                4 => [
                    'persist',
                    'remove',
                ],
            ],
            'fetch' => [
                4 => 2,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\Sikla0',
            ],
            'sourceToTargetKeyColumns' => [
                4 => [
                    'utilisateur_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                4 => [
                    'id' => 'utilisateur_id',
                ],
            ],
            'joinColumns' => [
                4 => [
                    $o[5],
                ],
            ],
            'joinColumnFieldNames' => [
                4 => [
                    'utilisateur_id' => 'utilisateur_id',
                ],
            ],
            'deferrable' => [
                5 => false,
            ],
            'unique' => [
                5 => true,
            ],
            'referencedColumnName' => [
                5 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'utilisateur',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\Utilisateur',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Transaction',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\TransactionRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'montant' => $o[2],
                    'date' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'montant' => 'montant',
                    'date' => 'date',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'montant' => 'montant',
                    'date' => 'date',
                ],
            ],
            'table' => [
                [
                    'name' => 'transaction',
                ],
            ],
            'associationMappings' => [
                [
                    'utilisateur' => $o[4],
                    'type' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Transaction',
                5 => 'utilisateur_id',
                7 => 'type_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'integer',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'montant',
                'date',
            ],
            'columnName' => [
                1 => 'id',
                'montant',
                'date',
            ],
            'fetch' => [
                4 => 2,
                6 => 2,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\Transaction',
                6 => 'App\\Entity\\Transaction',
            ],
            'sourceToTargetKeyColumns' => [
                4 => [
                    'utilisateur_id' => 'id',
                ],
                6 => [
                    'type_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                4 => [
                    'id' => 'utilisateur_id',
                ],
                6 => [
                    'id' => 'type_id',
                ],
            ],
            'joinColumns' => [
                4 => [
                    $o[5],
                ],
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                4 => [
                    'utilisateur_id' => 'utilisateur_id',
                ],
                6 => [
                    'type_id' => 'type_id',
                ],
            ],
            'deferrable' => [
                5 => false,
                7 => false,
            ],
            'unique' => [
                5 => false,
                7 => false,
            ],
            'nullable' => [
                5 => false,
                7 => false,
            ],
            'referencedColumnName' => [
                5 => 'id',
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'utilisateur',
                6 => 'type',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\Utilisateur',
                6 => 'App\\Entity\\TypeTransaction',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\TypeTransaction',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\TypeTransactionRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'libelle' => $o[2],
                    'signe' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'libelle' => 'libelle',
                    'signe' => 'signe',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'libelle' => 'libelle',
                    'signe' => 'signe',
                ],
            ],
            'table' => [
                [
                    'name' => 'type_transaction',
                ],
            ],
            'idGenerator' => [
                $o[4],
            ],
            'name' => [
                'App\\Entity\\TypeTransaction',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'integer',
            ],
            'fieldName' => [
                1 => 'id',
                'libelle',
                'signe',
            ],
            'columnName' => [
                1 => 'id',
                'libelle',
                'signe',
            ],
            'length' => [
                2 => 255,
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Utilisateur',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UtilisateurRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'email' => $o[3],
                    'code' => $o[4],
                    'adresse' => $o[5],
                    'telephone' => $o[6],
                    'fokontany' => $o[7],
                    'activite' => $o[8],
                    'nif' => $o[9],
                    'personne' => $o[10],
                    'date' => $o[11],
                    'solde' => $o[12],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'email' => 'email',
                    'code' => 'code',
                    'adresse' => 'adresse',
                    'telephone' => 'telephone',
                    'fokontany' => 'fokontany',
                    'activite' => 'activite',
                    'nif' => 'nif',
                    'personne' => 'personne',
                    'date' => 'date',
                    'solde' => 'solde',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'email' => 'email',
                    'code' => 'code',
                    'adresse' => 'adresse',
                    'telephone' => 'telephone',
                    'fokontany' => 'fokontany',
                    'activite' => 'activite',
                    'nif' => 'nif',
                    'personne' => 'personne',
                    'date' => 'date',
                    'solde' => 'solde',
                ],
            ],
            'table' => [
                [
                    'name' => 'utilisateur',
                ],
            ],
            'associationMappings' => [
                [
                    'parent' => $o[13],
                ],
            ],
            'idGenerator' => [
                $o[15],
            ],
            'name' => [
                'App\\Entity\\Utilisateur',
                14 => 'parent_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'string',
                'datetime',
                'integer',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'email',
                'code',
                'adresse',
                'telephone',
                'fokontany',
                'activite',
                'nif',
                'personne',
                'date',
                'solde',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'email',
                'code',
                'adresse',
                'telephone',
                'fokontany',
                'activite',
                'nif',
                'personne',
                'date',
                'solde',
            ],
            'length' => [
                2 => 255,
                255,
                7,
                255,
                30,
                255,
                255,
                50,
                30,
            ],
            'nullable' => [
                3 => true,
                5 => true,
                true,
                true,
                true,
                true,
                14 => true,
            ],
            'unique' => [
                3 => true,
                true,
            ],
            'fetch' => [
                13 => 2,
            ],
            'sourceEntity' => [
                13 => 'App\\Entity\\Utilisateur',
            ],
            'sourceToTargetKeyColumns' => [
                13 => [
                    'parent_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                13 => [
                    'id' => 'parent_id',
                ],
            ],
            'joinColumns' => [
                13 => [
                    $o[14],
                ],
            ],
            'joinColumnFieldNames' => [
                13 => [
                    'parent_id' => 'parent_id',
                ],
            ],
            'referencedColumnName' => [
                14 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                13 => 'parent',
            ],
            'targetEntity' => [
                13 => 'App\\Entity\\Utilisateur',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
