<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRvUm22x\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRvUm22x/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRvUm22x.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRvUm22x\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRvUm22x\App_KernelProdContainer([
    'container.build_hash' => 'RvUm22x',
    'container.build_id' => '627e9b4f',
    'container.build_time' => 1767385208,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRvUm22x');
