<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_database' => [[], ['_controller' => 'App\\Controller\\DatabaseController::index'], [], [['text', '/database']], [], [], []],
    'fetch_user_info' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\DatabaseController::get_user_info'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/info']], [], [], []],
    'fetch_user_transaction' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\DatabaseController::get_user_transaction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/transaction']], [], [], []],
    'fetch_user_parrainage' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\DatabaseController::get_user_parrainage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/parrainage']], [], [], []],
    'export' => [[], ['_controller' => 'App\\Controller\\DatabaseController::export'], [], [['text', '/export']], [], [], []],
    'access' => [[], ['_controller' => 'App\\Controller\\IndexController::acces'], [], [['text', '/']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\IndexController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\DatabaseController::index' => [[], ['_controller' => 'App\\Controller\\DatabaseController::index'], [], [['text', '/database']], [], [], []],
    'App\Controller\DatabaseController::get_user_info' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\DatabaseController::get_user_info'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/info']], [], [], []],
    'App\Controller\DatabaseController::get_user_transaction' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\DatabaseController::get_user_transaction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/transaction']], [], [], []],
    'App\Controller\DatabaseController::get_user_parrainage' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\DatabaseController::get_user_parrainage'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/parrainage']], [], [], []],
    'App\Controller\DatabaseController::export' => [[], ['_controller' => 'App\\Controller\\DatabaseController::export'], [], [['text', '/export']], [], [], []],
    'App\Controller\IndexController::acces' => [[], ['_controller' => 'App\\Controller\\IndexController::acces'], [], [['text', '/']], [], [], []],
    'App\Controller\IndexController::logout' => [[], ['_controller' => 'App\\Controller\\IndexController::logout'], [], [['text', '/logout']], [], [], []],
];
