<?php

namespace ContainerRvUm22x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DatabaseController' shared autowired service.
     *
     * @return \App\Controller\DatabaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DatabaseController'] = $instance = new \App\Controller\DatabaseController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\DatabaseController', $container));

        return $instance;
    }
}
