<?php

namespace ContainerRvUm22x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelUploadTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ExcelUploadType' shared autowired service.
     *
     * @return \App\Form\ExcelUploadType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ExcelUploadType'] = new \App\Form\ExcelUploadType();
    }
}
