<?php

namespace ContainerRvUm22x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSikla0RepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\Sikla0Repository' shared autowired service.
     *
     * @return \App\Repository\Sikla0Repository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\Sikla0Repository'] = new \App\Repository\Sikla0Repository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
