<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEf4dkGq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEf4dkGq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEf4dkGq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEf4dkGq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEf4dkGq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ef4dkGq',
    'container.build_id' => '37119180',
    'container.build_time' => 1767388175,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEf4dkGq');
