<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activite' => [parent::class, 'activite', null, 16],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'fokontany' => [parent::class, 'fokontany', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nif' => [parent::class, 'nif', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'parent' => [parent::class, 'parent', null, 16],
        "\0".parent::class."\0".'personne' => [parent::class, 'personne', null, 16],
        "\0".parent::class."\0".'solde' => [parent::class, 'solde', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'activite' => [parent::class, 'activite', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'fokontany' => [parent::class, 'fokontany', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nif' => [parent::class, 'nif', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'parent' => [parent::class, 'parent', null, 16],
        'personne' => [parent::class, 'personne', null, 16],
        'solde' => [parent::class, 'solde', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
